name: Test runner labels
on: workflow_dispatch
jobs:
  test-docker:
    runs-on: docker
    steps: [{ run: echo "docker works" }]
  test-ubuntu:
    runs-on: ubuntu-latest
    steps: [{ run: echo "ubuntu-latest works" }]
  test-selfhosted:
    runs-on: self-hosted
    steps: [{ run: echo "self-hosted works" }]
  test-linux:
    runs-on: linux
    steps: [{ run: echo "linux works" }]
  test-idk:
    runs-on: idk
    steps: [{ run: echo "idk works" }]
